### ISSUE TITLE
Is there a potential gotcha with internal function task tables that share the same names?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/ds-pipelines-3-course#27]
I have been moving many of my task table practices to use the pattern in this course. It is great!

As part of those moves, I have created some task tables that are fairly generic, such as a call per variable in the WQP (secchi, temperature, more). My task objects are generically named, such as `bbox_3038_data` or `pull_304_data`. In the end each of these objects doesn't really matter because I am focused on the result of the combiner - that is the thing I am saving and using. Now I am thinking I am creating some remake database collisions with this pattern, because there is a `pull_304_data` object in both `temperature` and `secchi` and unless `remake` is able to track the fact that these came from a different remake file, they probably collide in the database and cause unintended rebuilds. 

I have noticed a few rebuilds which I think are related to this, but haven't verified that it is indeed caused by my generic object/task naming. Here is how this looks in my workflow, which I am starting to see the flaws in:

For DOC (just a single task):
```yaml
  # --- bbox_154 --- #
  
  bbox_154_data:
    command: get_wqp_data(characteristicName = I('Organic carbon|Colored dissolved organic matter (CDOM)'), 
              bBox = I('-112.5,37.5,-105,45'), minresults = 10)
```
For temperature (just a single task):
```yaml
  # --- bbox_154 --- #
  
  bbox_154_data:
    command: get_wqp_data(characteristicName = I('Temperature|Temperature, sample|Temperature, water|Temperature, water, deg F'), 
              bBox = I('-157.5,17.5,-155,20'), minresults = 10)
```

I _think_ this issue would be solved by simply adding a short name to the object, such as `bbox_154_temperature_data`, but I haven't done that yet because in this particular case, the pipeline rebuild is a multi-day process(!). 

But it does make me wonder if this guidance (don't do this thing I did!) should show up either in this course or tips and tricks. 

Additionally, it did worry me that it seems pretty hard to clean up the objects in a huge task table. I am assuming that if I change my scheme, remake doesn't delete the old objects or the references to them, so they continue to live in the DB. This second issue is probably not a big pressing issue for most cases, but it did start to concern me a little bit as my computer's SSD continues to fill up 🤪
